### ISSUE TITLE
Stackoverflow when running all tests 

### ISSUE THREAD

**Issue by sharkAndshark** [apdevelop/linq2db-postgis-extensions#17]
Stackoverflow error get tests aborted.
```bash
git clone git@github.com:apdevelop/linq2db-postgis-extensions.git
cd linq2db-postgis-extensions
dotnet test
```
Run all tests with Visual Studio Test UI get this error too.

**Comment by apdevelop** [comment]
There is missed `STAsText` call in 

`Assert.AreEqual(ExpectedMultiPoint, db.Select(() => GeometryAccessors.STPoints(Wkt).STAsText()));`

fixed in `develop` branch now.
