### ISSUE TITLE
Update equal checks in test with tolerance

### ISSUE THREAD

**Issue by sharkAndshark** [apdevelop/linq2db-postgis-extensions#18]
Some tests fails on different version PostGIS,eg [TestSTTileEnvelop](https://github.com/apdevelop/linq2db-postgis-extensions/blob/c60d2914021e64b05d63b073d7686a1ee142b0ec/LinqToDBPostGisNetTopologySuite.Tests/GeometryConstructorsTests.cs#L358) (postgresql 11,PostGIS 3.1)
How about update tests like [TestSTTileEnvelop](https://github.com/apdevelop/linq2db-postgis-extensions/blob/c60d2914021e64b05d63b073d7686a1ee142b0ec/LinqToDBPostGisNetTopologySuite.Tests/GeometryConstructorsTests.cs#L358) with a [helper method](https://github.com/NetTopologySuite/NetTopologySuite/blob/c838c5061aa0f13d1fa65f828a868d790302ec06/test/NetTopologySuite.Tests.NUnit/GeometryTestCase.cs#L66)?

**Comment by sharkAndshark** [comment]
Test output content here
```
  Exception has occurred: CLR/NUnit.Framework.AssertionException
  “NUnit.Framework.AssertionException”类型的异常在 nunit.framework.dll 中发生，但未在用户代码中进行处理: '  Expected string length 108 but was 118. Strings differ at index 25.
  Expected: "POLYGON((-10018754.1713945 0,-10018754.1713945 10018754.17139..."
  But was:  "POLYGON((-10018754.171394622 0,-10018754.171394622 10018754.1..."
  ------------------------------------^'
   在 NUnit.Framework.Assert.ReportFailure(String message)
   在 LinqToDBPostGisNetTopologySuite.Tests.GeometryConstructorsTests.TestSTTileEnvelope() 在 /home/zhangyijun/Projects/linq2db-postgis-extensions/LinqToDBPostGisNetTopologySuite.Tests/GeometryConstructorsTests.cs 中: 第 358 行
```

**Comment by apdevelop** [comment]
Fixed in https://github.com/apdevelop/linq2db-postgis-extensions/commit/fc2ac65baaa32a8867a9f39c7eaf9e6bd934dd69 and  https://github.com/apdevelop/linq2db-postgis-extensions/commit/02edca74acfe562e644e2dc510452eb9caa96ff4 .
